#!/usr/bin/env python3
"""Generate or check a project's INDEX.md from source markdown files.

Usage:
  python3 scripts/project-index.py --root path/to/project
  python3 scripts/project-index.py --root path/to/project --check
  make project-index PROJECT=my-project
"""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import sys
from pathlib import Path

MANIFEST_NAME = ".index-manifest.json"
SKIP_NAMES = frozenset({"AGENTS.md", "INDEX.md", "README.md", MANIFEST_NAME})
SKIP_DIR_NAMES = frozenset({"templates", "applications", "artifacts", "drafts"})
FRONTMATTER_DESC = re.compile(
    r"(?ms)\A---\s*\n.*?^description:\s*(.+?)\s*$.*?\n---\s*\n"
)
ATX_HEADING = re.compile(r"(?m)^#\s+(.+)$")


def strip_frontmatter(content: str) -> str:
    text = content.lstrip("\ufeff")
    if not text.startswith("---"):
        return text
    lines = text.splitlines(keepends=True)
    if not lines or lines[0].strip() != "---":
        return text
    for idx in range(1, len(lines)):
        if lines[idx].strip() in ("---", "..."):
            return "".join(lines[idx + 1 :]).lstrip("\n")
    return text


def description_for(path: Path, content: str) -> str:
    match = FRONTMATTER_DESC.match(content.lstrip("\ufeff"))
    if match:
        desc = match.group(1).strip().strip("\"'")
        if desc:
            return desc
    body = strip_frontmatter(content)
    heading = ATX_HEADING.search(body)
    if heading:
        return heading.group(1).strip()
    return path.stem.replace("-", " ").replace("_", " ")


def iter_source_markdown(root: Path) -> list[Path]:
    files: list[Path] = []
    for path in sorted(root.rglob("*.md")):
        if not path.is_file():
            continue
        if path.name in SKIP_NAMES:
            continue
        rel_parts = path.relative_to(root).parts
        if any(part in SKIP_DIR_NAMES for part in rel_parts[:-1]):
            continue
        files.append(path)
    return files


def file_entry(path: Path, root: Path) -> dict:
    st = path.stat()
    return {
        "path": path.relative_to(root).as_posix(),
        "size": st.st_size,
        "mtime_ns": st.st_mtime_ns,
        "sha256": hashlib.sha256(path.read_bytes()).hexdigest(),
    }


def build_rows(root: Path) -> tuple[list[tuple[str, str]], list[dict]]:
    rows: list[tuple[str, str]] = []
    entries: list[dict] = []
    for path in iter_source_markdown(root):
        content = path.read_text(encoding="utf-8")
        rel = path.relative_to(root).as_posix()
        rows.append((rel, description_for(path, content)))
        entries.append(file_entry(path, root))
    rows.sort(key=lambda item: item[0])
    entries.sort(key=lambda item: item["path"])
    return rows, entries


def render_index(rows: list[tuple[str, str]]) -> str:
    lines = [
        "# Index",
        "",
        "Generated by `make project-index`. Do not hand-edit the table; add a",
        "`description:` field in each source file's YAML frontmatter instead.",
        "",
        "| Path | Description |",
        "| --- | --- |",
    ]
    if not rows:
        lines.append("| _(no source markdown)_ | Add notes under this project, then re-run `make project-index`. |")
    else:
        for rel, desc in rows:
            safe = desc.replace("|", "\\|")
            lines.append(f"| `{rel}` | {safe} |")
    lines.append("")
    return "\n".join(lines)


def load_manifest(root: Path) -> list[dict] | None:
    path = root / MANIFEST_NAME
    if not path.is_file():
        return None
    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return None
    files = payload.get("files") if isinstance(payload, dict) else None
    return files if isinstance(files, list) else None


def is_fresh(root: Path) -> bool:
    recorded = load_manifest(root)
    if recorded is None:
        return False
    if not (root / "INDEX.md").is_file():
        return False
    _, current = build_rows(root)
    if len(recorded) != len(current):
        return False
    by_path = {item["path"]: item for item in current}
    for item in recorded:
        if not isinstance(item, dict):
            return False
        key = item.get("path")
        if key not in by_path:
            return False
        cur = by_path[key]
        if (
            item.get("size") != cur["size"]
            or item.get("mtime_ns") != cur["mtime_ns"]
            or item.get("sha256") != cur["sha256"]
        ):
            return False
    return True


def write_index(root: Path) -> None:
    rows, entries = build_rows(root)
    index_text = render_index(rows)
    (root / "INDEX.md").write_text(index_text, encoding="utf-8")
    manifest = {
        "version": 1,
        "files": entries,
    }
    (root / MANIFEST_NAME).write_text(
        json.dumps(manifest, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--root",
        required=True,
        help="Project directory (contains AGENTS.md / source markdown)",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit 0 if INDEX.md matches the corpus; 1 if stale or missing",
    )
    args = parser.parse_args()
    root = Path(args.root).expanduser().resolve()
    if not root.is_dir():
        print(f"project-index: not a directory: {root}", file=sys.stderr)
        return 2

    if args.check:
        if is_fresh(root):
            print(f"project-index: fresh ({root})")
            return 0
        print(f"project-index: stale or missing ({root})", file=sys.stderr)
        return 1

    write_index(root)
    print(f"project-index: wrote {root / 'INDEX.md'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
